export const checkoutTypes = {
  SET_TOTAL: 'SET_TOTAL',
  LOAD_PLAN: 'LOAD_PLAN',
  DELETE_PLAN: 'DELETE_PLAN',
  RESET_STATE: 'RESET_STATE',
  LOAD_CAR_ITEM: 'LOAD_CAR_ITEM',
  UPDATE_CAR_ITEM: 'UPDATE_CAR_ITEM',
  DELETE_CAR_ITEM: 'DELETE_CAR_ITEM',
  LOAD_PERSONAL_DATA: 'LOAD_PERSONAL_DATA',
  LOAD_DESTINATION_DATA: 'LOAD_DESTINATION_DATA',
  SET_PERSONAL_DATA_FROM_STORAGE: 'SET_PERSONAL_DATA_FROM_STORAGE',
  SET_PAYPAL_ID: 'SET_PAYPAL_ID',
  SET_ID_PEDIDO_CREADO: 'SET_ID_PEDIDO_CREADO'
  // RESET_STATE: 'RESET_STATE'
}
